apiVersion: 1

datasources:
  - name: Athena (IoT Monitor)
    uid: athena-iot-monitor
    type: grafana-athena-datasource
    access: proxy
    jsonData:
      authType: default
      defaultRegion: ap-northeast-1
      catalog: AwsDataCatalog
      database: iot_monitor
      workgroup: iot-monitor
      outputLocation: $ATHENA_OUTPUT_LOCATION
    editable: false
