apiVersion: 1

datasources:
  - name: Infinity (IoT Monitor Cold)
    uid: infinity-iot-monitor-cold
    type: yesoreyeram-infinity-datasource
    access: proxy
    jsonData:
      auth_method: aws
      aws:
        authType: keys
        region: ap-northeast-1
        service: s3
      allowedHosts:
        - https://s3.ap-northeast-1.amazonaws.com
    secureJsonData:
      awsAccessKey: $INFINITY_AWS_ACCESS_KEY_ID
      awsSecretKey: $INFINITY_AWS_SECRET_ACCESS_KEY
    editable: false
